[package]
name = "abc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
proconio = "0.4.5"
rand = "0.8"
ac-library-rs = "=0.1.1"
itertools = "0.13.0"
rand_chacha = "0.3"
